import asyncio
import httpx

URL = "http://192.168.0.9:9000"

QUERIES = {
    "raw_daybook_fullyear.xml": """<ENVELOPE>
<HEADER><TALLYREQUEST>Export Data</TALLYREQUEST></HEADER>
<BODY><EXPORTDATA><REQUESTDESC>
<REPORTNAME>Day Book</REPORTNAME>
<STATICVARIABLES>
<SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT>
<SVCURRENTCOMPANY>RISHAB TRADING COMPANY</SVCURRENTCOMPANY>
<SVFROMDATE>20260401</SVFROMDATE>
<SVTODATE>20260613</SVTODATE>
</STATICVARIABLES>
</REQUESTDESC></EXPORTDATA></BODY>
</ENVELOPE>""",

    "raw_daybook_lastyear.xml": """<ENVELOPE>
<HEADER><TALLYREQUEST>Export Data</TALLYREQUEST></HEADER>
<BODY><EXPORTDATA><REQUESTDESC>
<REPORTNAME>Day Book</REPORTNAME>
<STATICVARIABLES>
<SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT>
<SVCURRENTCOMPANY>RISHAB TRADING COMPANY</SVCURRENTCOMPANY>
<SVFROMDATE>20250401</SVFROMDATE>
<SVTODATE>20260331</SVTODATE>
</STATICVARIABLES>
</REQUESTDESC></EXPORTDATA></BODY>
</ENVELOPE>""",

    "raw_ledger_vouchers_sample.xml": """<ENVELOPE>
<HEADER><TALLYREQUEST>Export Data</TALLYREQUEST></HEADER>
<BODY><EXPORTDATA><REQUESTDESC>
<REPORTNAME>Ledger Vouchers</REPORTNAME>
<STATICVARIABLES>
<SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT>
<SVCURRENTCOMPANY>RISHAB TRADING COMPANY</SVCURRENTCOMPANY>
<LEDGERNAME>Allied Enterprises</LEDGERNAME>
<SVFROMDATE>20260401</SVFROMDATE>
<SVTODATE>20260613</SVTODATE>
</STATICVARIABLES>
</REQUESTDESC></EXPORTDATA></BODY>
</ENVELOPE>""",

    "raw_stock_summary.xml": """<ENVELOPE>
<HEADER><TALLYREQUEST>Export Data</TALLYREQUEST></HEADER>
<BODY><EXPORTDATA><REQUESTDESC>
<REPORTNAME>Stock Summary</REPORTNAME>
<STATICVARIABLES>
<SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT>
<SVCURRENTCOMPANY>RISHAB TRADING COMPANY</SVCURRENTCOMPANY>
</STATICVARIABLES>
</REQUESTDESC></EXPORTDATA></BODY>
</ENVELOPE>""",

    "raw_trial_balance.xml": """<ENVELOPE>
<HEADER><TALLYREQUEST>Export Data</TALLYREQUEST></HEADER>
<BODY><EXPORTDATA><REQUESTDESC>
<REPORTNAME>Trial Balance</REPORTNAME>
<STATICVARIABLES>
<SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT>
<SVCURRENTCOMPANY>RISHAB TRADING COMPANY</SVCURRENTCOMPANY>
<SVFROMDATE>20260401</SVFROMDATE>
<SVTODATE>20260613</SVTODATE>
</STATICVARIABLES>
</REQUESTDESC></EXPORTDATA></BODY>
</ENVELOPE>""",

    "raw_balance_sheet.xml": """<ENVELOPE>
<HEADER><TALLYREQUEST>Export Data</TALLYREQUEST></HEADER>
<BODY><EXPORTDATA><REQUESTDESC>
<REPORTNAME>Balance Sheet</REPORTNAME>
<STATICVARIABLES>
<SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT>
<SVCURRENTCOMPANY>RISHAB TRADING COMPANY</SVCURRENTCOMPANY>
<SVFROMDATE>20260401</SVFROMDATE>
<SVTODATE>20260613</SVTODATE>
</STATICVARIABLES>
</REQUESTDESC></EXPORTDATA></BODY>
</ENVELOPE>""",

    "raw_cashflow.xml": """<ENVELOPE>
<HEADER><TALLYREQUEST>Export Data</TALLYREQUEST></HEADER>
<BODY><EXPORTDATA><REQUESTDESC>
<REPORTNAME>Cash Flow</REPORTNAME>
<STATICVARIABLES>
<SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT>
<SVCURRENTCOMPANY>RISHAB TRADING COMPANY</SVCURRENTCOMPANY>
<SVFROMDATE>20260401</SVFROMDATE>
<SVTODATE>20260613</SVTODATE>
</STATICVARIABLES>
</REQUESTDESC></EXPORTDATA></BODY>
</ENVELOPE>""",

    "raw_gst.xml": """<ENVELOPE>
<HEADER><TALLYREQUEST>Export Data</TALLYREQUEST></HEADER>
<BODY><EXPORTDATA><REQUESTDESC>
<REPORTNAME>GSTR-1</REPORTNAME>
<STATICVARIABLES>
<SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT>
<SVCURRENTCOMPANY>RISHAB TRADING COMPANY</SVCURRENTCOMPANY>
<SVFROMDATE>20260401</SVFROMDATE>
<SVTODATE>20260613</SVTODATE>
</STATICVARIABLES>
</REQUESTDESC></EXPORTDATA></BODY>
</ENVELOPE>"""
}

async def run():
    print("=== STARTING BATCH 2 DUMP ===")
    async with httpx.AsyncClient(timeout=120.0) as client:
        for name, payload in QUERIES.items():
            print(f"Fetching {name}...")
            try:
                resp = await client.post(URL, data=payload, headers={"Content-Type": "text/xml"})
                with open(name, "wb") as f:
                    f.write(resp.content)
                print(f"  -> Success: {len(resp.content)} bytes saved.")
            except Exception as e:
                print(f"  -> Error: {e}")

if __name__ == "__main__":
    asyncio.run(run())
